### ISSUE TITLE
tlshd refuses to load key material behind symlinks

### ISSUE THREAD

**Issue by WanzenBug** [oracle/ktls-utils#37]
In `tlshd_file_open()`, tlshd uses `openat2(..., RESOLVE_NO_SYMLINKS)`. This is in turn used to load the key material when nothing is provided via the keyring.

This seems overly strict, in my opinion. A lot of times certificates and keys are set up in a way they can be rotated by changing symlinks. For example, this is common when using Let's Encrypt with certbot, where the canonical location for key material is `/etc/letsencrypt/live/<host>/privkey.pem`, which are symlinks to `/etc/letsencrypt/archive/<host>/privkey$GENERATION.pem`. Every time the certificate gets renewed, the symlinks are updated.

Perhaps there is some security implication I am missing, but I would consider `tlshd.conf` as a trusted source, so I don't see the need for additional paranoia regarding symlinks.

**Comment by chucklever** [comment]
> In `tlshd_file_open()`, tlshd uses `openat2(..., RESOLVE_NO_SYMLINKS)`. This is in turn used to load the key material when nothing is provided via the keyring.
> 
> Perhaps there is some security implication I am missing, but I would consider `tlshd.conf` as a trusted source, so I don't see the need for additional paranoia regarding symlinks.

The idea is that an attacker can spoof tlshd into opening a malicious certificate by changing the symlink. But, perhaps that restriction could be security theatre. I can pass your request by our security reviewers to see if they agree to removing the open restriction.

**Comment by chucklever** [comment]
The security reviewers agree that LetsEncrypt is an important use case, and that we have fs.protected_symlinks now to prevent symlink TOCTOU races. I'll see about removing the restriction in ktls-utils-0.11.
