### ISSUE TITLE
Cannot build from source code

### ISSUE THREAD

**Issue by lchy12345** [oracle/ktls-utils#47]
i try the following but then there is error:

./autogen.sh
./configure --with-systemd --> error

./configure: line 5433: syntax error near unexpected token `0.9.0'
./configure: line 5433: `PKG_PROG_PKG_CONFIG(0.9.0)'

Then I cannot run "make" command.

It would be grateful if anyone could give a helping hand. Thanks in advance.

**Comment by stevedd** [comment]
On 2/5/24 5:14 AM, lchy12345 wrote:
> i try the following but then there is error:
> 
> ./autogen.sh
> ./configure --with-systemd --> error
> 
> ./configure: line 5433: syntax error near unexpected token |0.9.0' 
> ./configure: line 5433: |PKG_PROG_PKG_CONFIG(0.9.0)'
> 
> Then I cannot run "make" command.
> 
> It would be grateful if anyone could give a helping hand. Thanks in advance.
Works for me:
git clone https://github.com/oracle/ktls-utils
$ cd ktls-utils
$ ./autogen.sh
configure.ac:27: installing './compile'
configure.ac:22: installing './install-sh'
configure.ac:22: installing './missing'
src/tlshd/Makefile.am: installing './depcomp'
$ ./configure
configure: loading site script /usr/share/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for wchar.h... yes
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether _XOPEN_SOURCE should be defined... no
checking for gcc... (cached) gcc
checking whether the compiler supports GNU C... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to enable C11 features... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gnutls >= 3.3.0... yes
checking for libkeyutils... yes
checking for glib-2.0 >= 2.6... yes
checking for libnl-3.0 >= 3.1... yes
checking for gnutls_transport_is_ktls_enabled in -lgnutls... yes
checking for gnutls_protocol_set_enabled in -lgnutls... yes
checking for gnutls_get_system_config_file in -lgnutls... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/tlshd/Makefile
config.status: creating systemd/Makefile
config.status: creating config.h
config.status: executing depfiles commands
$ make
make  all-recursive
make[1]: Entering directory '/home/src/up/ktls-utils'
Making all in src
make[2]: Entering directory '/home/src/up/ktls-utils/src'
Making all in tlshd
make[3]: Entering directory '/home/src/up/ktls-utils/src/tlshd'
   CC       tlshd-client.o
   CC       tlshd-config.o
   CC       tlshd-handshake.o
   CC       tlshd-keyring.o
   CC       tlshd-ktls.o
   CC       tlshd-log.o
   CC       tlshd-main.o
   CC       tlshd-netlink.o
   CC       tlshd-server.o
   CCLD     tlshd
make[3]: Leaving directory '/home/src/up/ktls-utils/src/tlshd'
make[3]: Entering directory '/home/src/up/ktls-utils/src'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/src/up/ktls-utils/src'
make[2]: Leaving directory '/home/src/up/ktls-utils/src'
Making all in systemd
make[2]: Entering directory '/home/src/up/ktls-utils/systemd'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/src/up/ktls-utils/systemd'
make[2]: Entering directory '/home/src/up/ktls-utils'
make[2]: Leaving directory '/home/src/up/ktls-utils'
make[1]: Leaving directory '/home/src/up/ktls-utils'

steved

**Comment by chucklever** [comment]
> i try the following but then there is error:
> 
> ./autogen.sh ./configure --with-systemd --> error
> 
> ./configure: line 5433: syntax error near unexpected token `0.9.0' ./configure: line 5433: `PKG_PROG_PKG_CONFIG(0.9.0)'
> 
> Then I cannot run "make" command.

My guess is your build system is probably missing pkg-config.

**Comment by lchy12345** [comment]
Thanks so much. I am able to build after installing pkg-config and other required packages.

**Comment by stevedd** [comment]
On 2/5/24 9:28 PM, lchy12345 wrote:
> Thanks so much. I am able to build after installing pkg-config and other 
> required packages.
fair enough... what other packages were needed?

steved.

**Comment by lchy12345** [comment]
These packages:
pkg-config cmake-data gnutls-bin libgnutls28-dev libkeyutils-dev libglib2.0-dev libnl-3-dev libnl-genl-3-dev libgnutls30=3.7.3-4ubuntu1.4 libgmp10=2:6.2.1+dfsg-3ubuntu1
