### ISSUE TITLE
Cannot run tlshd

### ISSUE THREAD

**Issue by LZJ0913** [oracle/ktls-utils#52]
I experienced an error while running this **command**: 
`sudo ./tlshd -c ./tlshd.conf -s `
The following is the **error message** reproduced:
`tlshd[9499]: Built from ktls-utils 0.11-dev on Mar 30 2024 11:17:25`
`tlshd[9499]: x.509 priority string: SECURE256:+SECURE128:-COMP-ALL:-VERS-ALL:+VERS-TLS1.3:%NO_TICKETS:-CIPHER-ALL:+AES-256-GCM:+AES-128-GCM:+AES-128-CCM`
`tlshd[9499]: PSK priority string: SECURE256:+SECURE128:-COMP-ALL:-VERS-ALL:+VERS-TLS1.3:%NO_TICKETS:-CIPHER-ALL:+AES-256-GCM:+AES-128-GCM:+AES-128-CCM:+PSK:+DHE-PSK:+ECDHE-PSK`
`tlshd[9499]: PSK SHA256 priority string: SECURE256:+SECURE128:-COMP-ALL:-VERS-ALL:+VERS-TLS1.3:%NO_TICKETS:-CIPHER-ALL:+AES-128-GCM:+AES-128-CCM:+DHE-PSK:+ECDHE-PSK`
`tlshd[9499]: PSK SHA384 priority string: SECURE256:+SECURE128:-COMP-ALL:-VERS-ALL:+VERS-TLS1.3:%NO_TICKETS:-CIPHER-ALL:+AES-256-GCM:+DHE-PSK:+ECDHE-PSK`
`tlshd[9499]: Kernel handshake service is not available`
`tlshd[9499]: Shutting down.`
`DBG<1>/build/libnl3-3mLT0Q/libnl3-3.4.0/./lib/cache_mngt.c:308  nl_cache_mngt_unregister: Unregistered cache operations genl/family`

Following the instructions provided in tlshd.conf.man, I have configured **tlshd.conf**. The configuration content is as follows:
`[debug]`
`loglevel=1`
`tls=1`
`nl=1`
`[authenticate]`
`#keyrings= <keyring>;<keyring>;<keyring>`
`[authenticate.client]`
`x509.truststore= /home/Downloads/ktls-utils/cert/x509.truststore`
`x509.certificate= /home/Downloads/ktls-utils/cert/x509.certificate`
`x509.private_key= /home/Downloads/ktls-utils/cert/x509.private_key`
`[authenticate.server]`
`x509.truststore= /home/Downloads/ktls-utils/cert/x509.truststore`
`x509.certificate= /home/Downloads/ktls-utils/cert/x509.certificate`
`x509.private_key= /home/Downloads/ktls-utils/cert/x509.private_key`
By the way, I have tried different tools to create **x509.certificate  and x509.private_key** files, such as: **openssel** and **gnutls**.
I have been using the following command to configure **CONFIG_TLS**:
`sudo modprobe tls`
I ran the command `sudo ./tlshd -c ./tlshd.conf -s`, and afterward, I checked with `lsmod | grep tls`. I found that the returned information was `tls 114688 0`.

As I am not well-versed with TLS, could you please provide some ideas or guidance on how to resolve this issue? Any help would be greatly appreciated.

**Comment by chucklever** [comment]
> tlshd[9499]: Kernel handshake service is not available

This means your kernel does not support the TLS handshake service. Either the kernel release is too old or you don't have the TLS Kconfig options enabled in your kernel build.

**Comment by LZJ0913** [comment]
Thank you very much for your suggestion. I made the following attempts but still encountered the same error.

I tried `Ubuntu 20.04 LTS (5.15.0-101-generic)` and `Ubuntu 22.04 LTS (6.2.0-35-generic)`, both have Linux kernel versions **above 4.13**. And in the **/boot/config-$(uname -r)** configuration file, 'tls' seems to be a loadable module.
`CONFIG_TLS=m`
`CONFIG_TLS_DEVICE=y`
`# CONFIG_TLS_TOE is not set`

I used the following command to dynamically load the TLS module.
`$ modprobe tls`
`# echo tls >/etc/modules-load.d/tls.conf`
And checked whether it has been loaded successfully.
`$ modinfo tls`
`filename:       /lib/modules/6.2.0-35-generic/kernel/net/tls/tls.ko`
`alias:          tcp-ulp-tls`
`alias:          tls`
`license:        Dual BSD/GPL`
`description:    Transport Layer Security Support`
`author:         Mellanox Technologies`
`srcversion:     5AF1BC6903318F145BAA436`
`depends:        `
`retpoline:      Y`
`intree:         Y`
`name:           tls`
`vermagic:       6.2.0-35-generic SMP preempt mod_unload modversions `
`sig_id:         PKCS#7`
`signer:         Build time autogenerated kernel key`
`sig_key:        4C:AA...:E8:FE`
`sig_hashalgo:   sha512`
`signature:      80:5D:...:60:7A`

Maybe I still failed to enable TLS Kconfig options?

**Comment by chucklever** [comment]
None of the kernels you chose implement the TLS handshake service. You need a kernel newer than v6.5.

**Comment by chucklever** [comment]
That looks normal to me: tlshd is waiting for upcall requests from the kernel. "man tlshd.conf" explains how to boost logging verbosity if you want to see more detail.

**Comment by LZJ0913** [comment]
OK. I tried different configuration values in the `tls.conf` file, and found:
`loglevel=1`
`tls=4`
`nl=4`
then I can see different levels of debugging information, like **DBG<2>, DBG<3>, DBG<4>** etc.

**tlshd can run normally**, thank you very much.

**Comment by sammy007** [comment]
> None of the kernels you chose implement the TLS handshake service. **You need a kernel newer than v6.5.**

```
host tlshd[25045]: Handshake with ... was successful
```

6.1.0-18-amd64

**Comment by sammy007** [comment]
> None of the kernels you chose implement the TLS handshake service. You need a kernel newer than v6.5.

Please specify in README that nuance with kernel version, I have lost a lot of time with an issue when I had successful handshake and another service which is using ktls-utils refused to connect. It was pretty subtle, I am happy that I found your post. Thank you.
