### ISSUE TITLE
Tlshd.conf pathname is not ignoring spaces at the end of the path

### ISSUE THREAD

**Issue by olgakorn1** [oracle/ktls-utils#59]
My TLS handshake was failing and verbose output would only have a general ENOENT error for the open without a name but using the strace revealed that tlshd was trying to open a file "/root/server.crt " where only "/root/server.crt" (no space in the end) existed. 

The value in "authenticate.X" section for pathname is sensitive to appended spaces (possible tabs too).

**Comment by chucklever** [comment]
tlshd uses [g_key_file_get_string()](https://docs.gtk.org/glib/method.KeyFile.get_string.html) to extract pathnames from its config file. tlshd leaves each pathname string as an unprocessed UTF-8 string -- and one assumes, it will take everything to the end of the line.

It wouldn't be difficult to strip off white space at the end of the pathname, but tlshd would have to handle this processing itself.
