### ISSUE TITLE
Systemd service failed on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by davidchuyaya** [oracle/ktls-utils#72]
I am running on Ubuntu 24.04 LTS.

I installed the dependencies as suggested by Issue #47:
```
sudo apt install -y automake pkg-config cmake-data gnutls-bin libgnutls28-dev libkeyutils-dev libglib2.0-dev libnl-3-dev libnl-genl-3-dev
```
I removed the last 2 dependencies `libgnutls30=3.7.3-4ubuntu1.4` and `libgmp10=2:6.2.1+dfsg-3ubuntu1` since they could not be found.
If I attempt to install `libgnutls30` and `libgmp10` it will say they are already installed.

Then I cloned this repo and followed installation instructions, with no errors:
```bash
git clone https://github.com/oracle/ktls-utils
cd ktls-utils
./autogen.sh
./configure --with-systemd
make
sudo make install
sudo systemctl daemon-reload
sudo systemctl enable --now tlshd
```

When I run `sudo systemctl`, I see `tlshd.service` listed as `loaded failed failed` (corresponding to the fields LOAD ACTIVE SUB).

**Comment by chucklever** [comment]
Any interesting relevant messages in `journalctl -b` output?

**Comment by davidchuyaya** [comment]
I see
```
Jul 19 16:51:42 davidchu tlshd[373]: Failed to load config file: No such file or directory
```

Right before it shuts down.

**Comment by davidchuyaya** [comment]
I fixed it with this line:
```bash
sudo touch /etc/tlshd.conf
```
Based on the config file name expected in main.c.

Thanks!

**Comment by chucklever** [comment]
> I fixed it with this line:
> 
> ```shell
> sudo touch /etc/tlshd.conf
> ```
> 
> Based on the config file name expected in main.c.

There's a tlshd.conf file in the source code. Why didn't "make install" copy that into place?

**Comment by davidchuyaya** [comment]
When I ran `sudo make install`, it actually placed the file in `/usr/etc`:

```
davidchu@davidchu:~/ktls-utils$ sudo make install
Making install in src
make[1]: Entering directory '/home/davidchu/ktls-utils/src'
Making install in tlshd
make[2]: Entering directory '/home/davidchu/ktls-utils/src/tlshd'
make[3]: Entering directory '/home/davidchu/ktls-utils/src/tlshd'
 /usr/bin/mkdir -p '/usr/etc'
 /usr/bin/install -c -m 644 tlshd.conf '/usr/etc'
 /usr/bin/mkdir -p '/usr/sbin'
  /usr/bin/install -c tlshd '/usr/sbin'
 /usr/bin/mkdir -p '/usr/share/man/man5'
 /usr/bin/install -c -m 644 'tlshd.conf.man' '/usr/share/man/man5/tlshd.conf.5'
 /usr/bin/mkdir -p '/usr/share/man/man8'
 /usr/bin/install -c -m 644 'tlshd.man' '/usr/share/man/man8/tlshd.8'
make[3]: Leaving directory '/home/davidchu/ktls-utils/src/tlshd'
```

**Comment by davidchuyaya** [comment]
The distro-packaged version does place the config file correctly in `/etc/tlshd.conf`, which I did not modify.
Am I supposed to place the keyrings, certificates, and private keys in it?

The error pops up in both the distro and my hand-installed package, whenever I call either `tls_server_hello_x509` or `tls_client_hello_x509` from my kernel module. I'm not sure what that error means, aside from the fact that it's emerging from [this line](https://github.com/oracle/ktls-utils/blob/e55cefda944595fd83b609eba7ad8f819fa1c9d3/src/tlshd/netlink.c#L170), so if you have an idea as to what it might be related to, I can dig around and try to find out.

If it would be helpful, this is [how I'm setting up the keyring, cert, and privkeys](https://github.com/davidchuyaya/rollbaccine/tree/main/src#tls), and this is [how I'm calling `tls_client_hello_x509`](https://github.com/davidchuyaya/rollbaccine/blob/main/src/network/server.c#L744), but please feel no obligation to read any of my code.

**Comment by chucklever** [comment]
> The distro-packaged version does place the config file correctly in `/etc/tlshd.conf`, which I did not modify. Am I supposed to place the keyrings, certificates, and private keys in it?

Yes, for the moment, tlshd uses /etc/tlshd.conf to determine where to find the host's peer authentication material. So add pathnames to the certificates and CA bundles to /etc/tlshd.conf.

Currently, keyrings are known to work only for PSK handshakes.

**Comment by davidchuyaya** [comment]
Thank you, everything works now :)

We ended up using the hand-installed version since the distro version's config doesn't support truststores yet.
