### ISSUE TITLE
TLS protocol version & cipher suites

### ISSUE THREAD

**Issue by leo9800** [oracle/ktls-utils#76]
Given that the *kTLS* (TLS implementation in Linux Kernel) could only handle `Application Data` packets, could we assume that the TLS handshake is handled by *GnuTLS* and the master secret negotiated is somehow passed to the kernel *kTLS*?

If so, thus, could we therefore assume the TLS protocol version & cipher suites are dictated by `/etc/gnutls/config`? (configuration file for *GnuTLS*)

**Comment by chucklever** [comment]
> Given that the kTLS (TLS implementation in Linux Kernel) could only handle Application Data packets, could we assume that the TLS handshake is handled by GnuTLS and the master secret negotiated is somehow passed to the kernel kTLS?

Yes, that's how it works. The kernel passes an open socket up to tlshd, which performs the TLS handshake using GnuTLS.

> If so, thus, could we therefore assume the TLS protocol version & cipher suites are dictated by /etc/gnutls/config? (configuration file for GnuTLS)

I believe you can use /etc/gnutls/config to restrict the set of handshake-negotiated encryption algorithms. You can't add algorithms that the kernel / NIC do not implement.
