### ISSUE TITLE
configure: dependency check for libnl-genl-3 is missing

### ISSUE THREAD

**Issue by igaw** [oracle/ktls-utils#77]
The configure step is successful but when linking:

```
/usr/bin/ld: cannot find -lnl-genl-3: No such file or directory
```

This is on debian unstable

**Comment by chucklever** [comment]
Commit 4698a748ad08 ("tlshd: link in libnl-3 for upcoming netlink support") added:

+PKG_CHECK_MODULES([LIBNL3], libnl-3.0 >= 3.1)
+AC_SUBST([LIBNL3_CFLAGS])
+AC_SUBST([LIBNL3_LIBS])

to configure.ac. Is this check wrong?

**Comment by igaw** [comment]
Ah okay. Let me check what is going on on Debian.
