### ISSUE TITLE
session keyring for lookup too limited?

### ISSUE THREAD

**Issue by igaw** [oracle/ktls-utils#79]
I am working on getting the nvme-tls use case bit more user friendly with nvme-cli.

My test setup consist out of my local machine running Tumbleweed and a remote Debian (unstable) box. While on Tumbleweed  `keyctl show` will show the inserted nvme-tls keys on any root shell.  On the remote Debian box (login via ssh) I only see the keys showing up on the shell which I used insert the keys. 

When `tlshd` is running as daemon (started by systemd), it doesn't seeing the keys either. The `nvme connect` will work if I run `tlshd` on the Debian box in the same shell where I inserted the keys into the kernel.

I  suspect the problem might be because the key lookup is using the `KEY_SPEC_SESSION_KEYRING` keyring:

https://github.com/oracle/ktls-utils/blob/236756a0691410aefe517bda727a93e9e6724892/src/tlshd/server.c#L304

```
Oct 09 17:49:10 nvmet tlshd[10312]: Querying the handshake service
Oct 09 17:49:10 nvmet tlshd[10312]: Parsing a valid netlink message
Oct 09 17:49:10 nvmet tlshd[10312]: No certificates found
Oct 09 17:49:10 nvmet tlshd[10312]: System config file: /etc/gnutls/config
Oct 09 17:49:10 nvmet tlshd[10312]: failed to search key
Oct 09 17:49:10 nvmet tlshd[10312]: gnutls: Error in password/key file. (-31)
Oct 09 17:49:10 nvmet tlshd[10312]: Handshake with 'flourine.lan' (192.168.154.187) failed
Oct 09 17:41:35 nvmet tlshd[10282]: failed to search key
```

I haven't really figured out if this is a bug or not or if this works as designed. On my local machine the keys are accessible, just not on Debian when setting up the target side.

**Comment by chucklever** [comment]
You might need to inform tlshd about the keyring it needs to search using /etc/tlshd.conf .

**Comment by igaw** [comment]
Indeed, this was it! After adding `keyrings = .nvme` to the `/etc/tlshd.conf` file, it works as expected.

Sorry for the noise.
