### ISSUE TITLE
Release ktls-utils 0.11 tag

### ISSUE THREAD

**Issue by igaw** [oracle/ktls-utils#82]
The `ktls-utils-0.11` tag is not pointing to the `Release ktls-utils 0.11` commit in the main branch. Is this on purpose? I noticed this while updating our SUSE packages.

**Comment by chucklever** [comment]
I don't know how shit like that happens. Should a new release be cut to ensure that the provenance of 0.11 is correct?

**Comment by igaw** [comment]
git is very good in making the user look stupid. I can't remember how many times I screwed up. So don't worry.

Not sure what's best here. Maybe if there is correct 0.12 tag eventually no one will care. It's just our tooling told me that it's technically still a 0.10 release.

**Comment by chucklever** [comment]
> Maybe if there is correct 0.12 tag eventually no one will care.

That was my thought as well. Use this mistake as an object lesson to check each release more carefully.

**Comment by igaw** [comment]
FWIW, I am usually writing release scripts, because I was butchering releases one after the other. Since then it got way better. Though there are still small hickups but keep fixing/improving these release scripts and there is clear trend:

https://github.com/linux-nvme/nvme-cli/blob/master/scripts/release.sh

**Comment by chucklever** [comment]
Thank you for the script!
